start : header cross_section+

header : "NSECT" "=" INT NEWLINE "FORMRF" "=" NUMBER NEWLINE "WALLRF" "=" NUMBER NEWLINE

cross_section: topoid river_name chainage property* profile

topoid: STRING NEWLINE
river_name: STRING NEWLINE
chainage: NUMBER NEWLINE

property: formrf
        | manningrf
        | bankd90
        | storage
        | bedrock
        | lsf

formrf: ("FORMRF" | "FOR") NEWLINE NUMBER NEWLINE
manningrf: ("MANNINGRF" | "MAN") NEWLINE NUMBER NEWLINE
bankd90: "BANKD90" NEWLINE NUMBER NEWLINE
storage: ("STORAGE" | "STO") NEWLINE INT INT NEWLINE
bedrock: "BEDROCK RL" NEWLINE NUMBER NEWLINE
lsf: "LSF" NEWLINE NUMBER NEWLINE

profile: ("PROFILE" | "PRO") NEWLINE point point point point "***" NEWLINE?
point: NUMBER NUMBER NEWLINE

STRING : /[^\n]+/

%import common.INT
%import common.SIGNED_NUMBER -> NUMBER
%import common.WS_INLINE
%import common.NEWLINE
%ignore WS_INLINE

COMMENT: /![^\n]*/
%ignore COMMENT
